"""Create all

Revision ID: 5736c11bc201
Revises: 2ed8a8bb0037
Create Date: 2025-06-02 15:12:55.417488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5736c11bc201'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('login', name='uq_user_login')
    )
    op.create_table('videos',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('length_seconds', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.Date(), nullable=False),
    sa.Column('author_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('author_uuid', 'name', name='uq_video_name_author')
    )
    op.create_index('ix_video_author_uuid', 'videos', ['author_uuid'], unique=False)
    op.create_table('heat_maps',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('video_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['video_uuid'], ['videos.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('video_uuid', name='uq_heat_map_video')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heat_maps')
    op.drop_index('ix_video_author_uuid', table_name='videos')
    op.drop_table('videos')
    op.drop_table('users')
    # ### end Alembic commands ###
